# Where should we write the GIF?
Output  lis.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 25
Set Width 1000
Set Height 900
Set Theme Laser
Set Framerate 60

# Type a command in the terminal.
Type go run ../.

# Pause for dramatic effect...
Sleep 500ms

# Run the command by pressing enter.
Enter
Sleep 500ms
Down 2 
Sleep 300ms 
Up 2 
Sleep 300ms 
Enter 3 
Sleep 300ms 
Down 1 
Sleep 300ms 
Type "q"

# Admire the output for a bit.
Sleep 25s