# Where should we write the GIF?
Output  gla2.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 16
Set Width 1100
Set Height 1000
Set Theme Laser
Set Framerate 60

# Type a command in the terminal.
Type go run ../.

# Pause for dramatic effect...
Sleep 500ms

# Run the command by pressing enter.
Enter
Sleep 500ms
Sleep 500ms
Down 10 
Sleep 500ms
Up 10 
Sleep 500ms
Type "q"
Sleep 500ms

# Admire the output for a bit.
Sleep 25s